<?php

namespace Database\Seeders;

use App\Models\Control;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Import wewnętrznego katalogu kontroli (Control) z Macierzy Mapowania Kontroli
 * TSH-SEC-Control-Mapping-Matrix, dostarczone przez CSO. Katalog Control był
 * dotąd pusty — to pierwsze rzeczywiste dane w tej tabeli.
 *
 * Historia importu:
 * - v3.0 (2026-07-13): 58 kontroli w 11 domenach (Governance, Access Control,
 *   Endpoint, Network, Secure Development, Incident Management, Business
 *   Continuity, Data Protection, Supply Chain, People, Physical).
 * - v3.1 (2026-07-14): matryca zreorganizowana na 66 wierszy / 13 domen
 *   (dodano m.in. Vulnerability Management, Privacy & Data Protection oraz
 *   Regional & Jurisdictional Compliance KSA/USA; kolumny KSA-Specific
 *   Reference i US-Specific Reference). Zastosowano scalenie nieniszczące
 *   (decyzja CSO): wszystkie 58 istniejących kodów CTRL-* zachowane bez zmian
 *   (ciągłość powiązanych Findings/Evidence/Testów), dodano 16 nowych kontroli
 *   (CTRL-GOV-010, CTRL-NET-005/006, CTRL-VULN-001, CTRL-DATA-006/007/008,
 *   CTRL-PPL-006/007, CTRL-INTL-001..007) dla pozycji nieobecnych we
 *   wcześniejszym katalogu. Domena "Physical Security" (CTRL-PHYS-001..003)
 *   zniknęła z matrycy v3.1 mimo że POL-011/POL-012 nadal obowiązują — te 3
 *   kontrole NIE są kasowane (kaskadowo usunęłoby powiązane Findings/Evidence/
 *   Testy), tylko oznaczone is_applicable=false z wyjaśnieniem w
 *   applicability_statement. CTRL-GOV-003/007 zaktualizowane — POL-016 w
 *   Podręczniku Polityk v3.1 oznacza teraz Change Management, nie Operational
 *   Risk, więc referencje do POL-016 usunięto z ich opisów.
 *
 * Odwzorowania na ramy (ISO/IEC 27001 Annex A, NIST SP 800-53, NIST CSF 2.0,
 * NCA ECC-1:2018, ISO/IEC 27701) są zapisane czytelnie w polu description —
 * NIE są linkowane przez pivot frameworkControls(), ponieważ istniejący
 * katalog FrameworkControl (seedowany wcześniej) nie ma wypełnionego pola
 * clause_ref dla ISO27001/NIST_CSF, więc precyzyjne auto-dopasowanie kodu
 * klauzuli (np. "A.5.1") do rekordu FrameworkControl nie jest możliwe bez
 * ręcznej weryfikacji. Uzupełnienie clause_ref i właściwe podpięcie pivotów
 * to osobne zadanie następcze.
 *
 * Idempotentny — bezpieczny do wielokrotnego uruchomienia.
 */
class TshSecControlMappingSeeder extends Seeder
{
    private function items(): array
    {
        return [
            [
                'code' => 'CTRL-GOV-001',
                'name' => 'Information Security Policy — approved by Management Board',
                'description' => 'Information Security Policy — approved by Management Board. TSH policy/document: POL-001 v2.4. Evidence: Policy Manual (POL-001). Framework mapping: ISO/IEC 27001:2022 Annex A A.5.1 · NIST SP 800-53 Rev.5 PM-1, PM-2 · NIST CSF 2.0 GV.PO 1-1.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Governance & Risk Management".',
                'policy_code' => 'POL-001',
            ],
            [
                'code' => 'CTRL-GOV-002',
                'name' => 'Security roles & responsibilities defined (RACI)',
                'description' => 'Security roles & responsibilities defined (RACI). TSH policy/document: REG-003 RACI Matrix. Evidence: RACI Matrix. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.2 · NIST SP 800-53 Rev.5 PM-2, PS-7 · NIST CSF 2.0 GV.RR 1-2.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Governance & Risk Management".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-GOV-003',
                'name' => 'Risk appetite and risk acceptance defined',
                'description' => 'Risk appetite and risk acceptance defined. TSH policy/document: POL-001 v2.4, REG-001. Evidence: Risk Register REG-001. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.8 · NIST SP 800-53 Rev.5 RA-2, PM-9 · NIST CSF 2.0 GV.RM 1-4.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Governance & Policy". [v3.1] Reassigned from POL-016 to POL-001 — POL-016 now denotes Change Management, not Operational Risk.',
                'policy_code' => 'POL-001',
            ],
            [
                'code' => 'CTRL-GOV-004',
                'name' => 'Annual management review of ISMS',
                'description' => 'Annual management review of ISMS. TSH policy/document: PROC-212, CLT-410. Evidence: Management review record. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.35 · NIST SP 800-53 Rev.5 CA-2, PM-10 · NIST CSF 2.0 GV.OC 1-3.',
                'control_type' => 'Detective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Governance & Risk Management".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-GOV-005',
                'name' => 'Security exception process',
                'description' => 'Security exception process. TSH policy/document: POL-017, REG-012. Evidence: Exception Register REG-012. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.1 · NIST SP 800-53 Rev.5 PM-9 · NIST CSF 2.0 GV.PO.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Governance & Risk Management".',
                'policy_code' => 'POL-017',
            ],
            [
                'code' => 'CTRL-GOV-006',
                'name' => 'Annual information security risk assessment',
                'description' => 'Annual information security risk assessment. TSH policy/document: PROC-206, REG-001. Evidence: Risk Register REG-001. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.2 · NIST SP 800-53 Rev.5 RA-3, RA-5 · NIST CSF 2.0 ID.RA 2-1 · ISO/IEC 27701:2019 7.2.2.',
                'control_type' => 'Detective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Governance & Risk Management".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-GOV-007',
                'name' => 'Operational risk register (REG-011) — separate from ISMS risk register',
                'description' => 'Operational risk register (REG-011), maintained separately from the ISMS risk register (REG-001). TSH policy/document: REG-011, PROC-213. Evidence: REG-011 Operational Risk Register. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.29 · NIST SP 800-53 Rev.5 CP-2 · NIST CSF 2.0 GV.RM.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'monthly',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Business Continuity & Resilience" (moved from Governance & Policy in v3.0). [v3.1] Reassigned from POL-016 — POL-016 now denotes Change Management, not Operational Risk; the operational risk process is now referenced only via REG-011/PROC-213, without a standalone policy.',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-GOV-008',
                'name' => 'Security KPI/KRI dashboard',
                'description' => 'Security KPI/KRI dashboard. TSH policy/document: REG-013. Evidence: REG-013 KPI Dashboard. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.35 · NIST SP 800-53 Rev.5 PM-6 · NIST CSF 2.0 GV.MT 1-4.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Governance & Risk Management".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-GOV-009',
                'name' => 'Compliance obligation tracking',
                'description' => 'Compliance obligation tracking. TSH policy/document: REG-014, PROC-215. Evidence: REG-014 Obligation Register. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.36 · NIST SP 800-53 Rev.5 CA-1, PM-1 · NIST CSF 2.0 GV.PO 1-3.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Governance & Risk Management".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-IAM-001',
                'name' => 'Multi-factor authentication — all users mandatory',
                'description' => 'Multi-factor authentication — all users mandatory. TSH policy/document: POL-003, CFG-302. Evidence: Entra ID MFA reports. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.5 · NIST SP 800-53 Rev.5 IA-2, IA-5 · NIST CSF 2.0 PR.AA 3-1.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Access Control & Identity".',
                'policy_code' => 'POL-003',
            ],
            [
                'code' => 'CTRL-IAM-002',
                'name' => 'Privileged access management — PIM JIT (max 4h)',
                'description' => 'Privileged access management — PIM JIT (max 4h). TSH policy/document: POL-003, CFG-302. Evidence: Entra ID PIM activation logs. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.18 · NIST SP 800-53 Rev.5 AC-2, AC-6 · NIST CSF 2.0 PR.AA 3-1.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Access Control & Identity".',
                'policy_code' => 'POL-003',
            ],
            [
                'code' => 'CTRL-IAM-003',
                'name' => 'SSO via Entra ID — all corporate applications',
                'description' => 'SSO via Entra ID — all corporate applications. TSH policy/document: CFG-302. Evidence: Entra ID SAML config. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.2 · NIST SP 800-53 Rev.5 IA-8, AC-17 · NIST CSF 2.0 PR.AA 3-1.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Access Control & Identity".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-IAM-004',
                'name' => 'Least privilege — role-based access control',
                'description' => 'Least privilege — role-based access control. TSH policy/document: POL-003, CFG-302. Evidence: Entra ID RBAC config. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.3 · NIST SP 800-53 Rev.5 AC-3, AC-6 · NIST CSF 2.0 PR.AA 3-1.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Access Control & Identity".',
                'policy_code' => 'POL-003',
            ],
            [
                'code' => 'CTRL-IAM-005',
                'name' => 'Quarterly access reviews',
                'description' => 'Quarterly access reviews. TSH policy/document: POL-003, REG-003. Evidence: Access review records. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.5 · NIST SP 800-53 Rev.5 AC-2, IA-4 · NIST CSF 2.0 PR.AA 3-2.',
                'control_type' => 'Detective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'quarterly',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Access Control & Identity".',
                'policy_code' => 'POL-003',
            ],
            [
                'code' => 'CTRL-IAM-006',
                'name' => 'Account deprovisioning — 1h SLA (involuntary)',
                'description' => 'Account deprovisioning — 1h SLA (involuntary). TSH policy/document: PROC-211. Evidence: Offboarding checklist PROC-211. Framework mapping: ISO/IEC 27001:2022 Annex A A.6.5 · NIST SP 800-53 Rev.5 PS-4, AC-2 · NIST CSF 2.0 PR.AA 3-5.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Access Control & Identity".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-END-001',
                'name' => 'MDM — all Apple devices via IRU (Apple MDM)',
                'description' => 'MDM — all Apple devices via IRU (Apple MDM). TSH policy/document: CFG-303, CFG-305. Evidence: IRU compliance report. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.1 · NIST SP 800-53 Rev.5 CM-6, SC-28 · NIST CSF 2.0 PR.PS 4-3.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Endpoint Security".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-END-002',
                'name' => 'MDM — Windows via Microsoft Intune',
                'description' => 'MDM — Windows via Microsoft Intune. TSH policy/document: CFG-303. Evidence: Intune compliance report. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.1 · NIST SP 800-53 Rev.5 CM-6, SC-28 · NIST CSF 2.0 PR.PS 4-3.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Endpoint Security".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-END-003',
                'name' => 'EDR — MDE on all managed devices',
                'description' => 'EDR — MDE on all managed devices. TSH policy/document: CFG-303. Evidence: MDE Security Portal. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.7 · NIST SP 800-53 Rev.5 SI-3, IR-4 · NIST CSF 2.0 DE.CM 4-3.',
                'control_type' => 'Preventive',
                'automation_level' => 'Automated',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Endpoint Security".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-END-004',
                'name' => 'Full-disk encryption — FileVault/BitLocker',
                'description' => 'Full-disk encryption — FileVault/BitLocker. TSH policy/document: POL-010, CFG-303. Evidence: IRU/Intune compliance. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.24 · NIST SP 800-53 Rev.5 SC-28 · NIST CSF 2.0 PR.DS 4-1.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Endpoint Security".',
                'policy_code' => 'POL-010',
            ],
            [
                'code' => 'CTRL-END-005',
                'name' => 'Patch management — 48h Critical SLA',
                'description' => 'Patch management — 48h Critical SLA. TSH policy/document: PROC-203, CFG-303. Evidence: IRU/Intune patch reports. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.8 · NIST SP 800-53 Rev.5 SI-2, RA-5 · NIST CSF 2.0 ID.RA 4-3.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Endpoint Security".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-END-006',
                'name' => 'BYOD — MDM MAM with data isolation',
                'description' => 'BYOD — MDM MAM with data isolation. TSH policy/document: POL-005, CFG-305. Evidence: IRU MAM policy. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.1 · NIST SP 800-53 Rev.5 AC-20, MP-7 · NIST CSF 2.0 PR.PS 4-3.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Endpoint Security".',
                'policy_code' => 'POL-005',
            ],
            [
                'code' => 'CTRL-END-007',
                'name' => 'DLP — three-layer (Google / MDE / IRU MAM)',
                'description' => 'DLP — three-layer (Google / MDE / IRU MAM). TSH policy/document: POL-014, CFG-308. Evidence: CFG-308 DLP config. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.12 · NIST SP 800-53 Rev.5 SI-12, MP-7 · NIST CSF 2.0 PR.DS 4-5.',
                'control_type' => 'Preventive',
                'automation_level' => 'Automated',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Endpoint Security".',
                'policy_code' => 'POL-014',
            ],
            [
                'code' => 'CTRL-NET-001',
                'name' => 'Conditional Access — blocks unmanaged devices',
                'description' => 'Conditional Access — blocks unmanaged devices. TSH policy/document: CFG-302. Evidence: Entra ID CA001-CA010. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.20 · NIST SP 800-53 Rev.5 SC-7, AC-17 · NIST CSF 2.0 PR.AA 4-2.',
                'control_type' => 'Preventive',
                'automation_level' => 'Automated',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Network & Communication Security".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-NET-002',
                'name' => 'VPN for public networks — enforced by MDM',
                'description' => 'VPN for public networks — enforced by MDM. TSH policy/document: POL-005, CFG-303. Evidence: IRU/Intune VPN profile. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.21 · NIST SP 800-53 Rev.5 SC-7, SC-28 · NIST CSF 2.0 PR.PS 4-2.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Network & Communication Security".',
                'policy_code' => 'POL-005',
            ],
            [
                'code' => 'CTRL-NET-003',
                'name' => 'Email authentication — SPF+DKIM+DMARC (p=reject)',
                'description' => 'Email authentication — SPF+DKIM+DMARC (p=reject). TSH policy/document: CFG-301, POL-014. Evidence: DNS records; DMARC reports. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.23 · NIST SP 800-53 Rev.5 SC-8, SI-8 · NIST CSF 2.0 PR.DS 4-2.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Network & Communication Security".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-NET-004',
                'name' => 'Cryptographic controls — AES-256, TLS 1.3, FIDO2',
                'description' => 'Cryptographic controls — AES-256, TLS 1.3, FIDO2. TSH policy/document: POL-010. Evidence: POL-010 approved algorithms. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.24 · NIST SP 800-53 Rev.5 SC-8, SC-28 · NIST CSF 2.0 PR.DS 4-1.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Network & Communication Security".',
                'policy_code' => 'POL-010',
            ],
            [
                'code' => 'CTRL-DEV-001',
                'name' => 'Secure SDLC — OWASP ASVS Level 2 standard',
                'description' => 'Secure SDLC — OWASP ASVS Level 2 standard. TSH policy/document: PROC-204. Evidence: PROC-204 documentation. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.25 · NIST SP 800-53 Rev.5 SA-3, SA-8 · NIST CSF 2.0 PR.PS 4-4.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Secure Development".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-DEV-002',
                'name' => 'SAST — CodeQL + Semgrep (CI/CD blocking gate)',
                'description' => 'SAST — CodeQL + Semgrep (CI/CD blocking gate). TSH policy/document: PROC-204, CFG-304. Evidence: GitHub Security Overview. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.28 · NIST SP 800-53 Rev.5 SA-11, SI-3 · NIST CSF 2.0 DE.CM 4-4.',
                'control_type' => 'Preventive',
                'automation_level' => 'Automated',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Secure Development".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-DEV-003',
                'name' => 'SCA — Snyk + Dependabot (CVE blocking gate)',
                'description' => 'SCA — Snyk + Dependabot (CVE blocking gate). TSH policy/document: PROC-204, CFG-304. Evidence: Dependabot/Snyk reports. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.22 · NIST SP 800-53 Rev.5 RA-5, SA-22 · NIST CSF 2.0 ID.RA 4-4.',
                'control_type' => 'Preventive',
                'automation_level' => 'Automated',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Secure Development".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-DEV-004',
                'name' => 'Secret scanning + push protection',
                'description' => 'Secret scanning + push protection. TSH policy/document: CFG-304, REF-017. Evidence: GitHub Advanced Security. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.28 · NIST SP 800-53 Rev.5 SA-11, SI-12 · NIST CSF 2.0 DE.CM 4-4.',
                'control_type' => 'Detective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Secure Development".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-DEV-005',
                'name' => 'SBOM delivery with every production release',
                'description' => 'SBOM delivery with every production release. TSH policy/document: PROC-204. Evidence: SBOM artefacts in CI/CD. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.22 · NIST SP 800-53 Rev.5 SA-17, SR-3 · NIST CSF 2.0 ID.SC 4-4.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Secure Development".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-IR-001',
                'name' => 'Incident classification P1–P4',
                'description' => 'Incident classification P1–P4. TSH policy/document: POL-007. Evidence: POL-007 IR Policy. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.24 · NIST SP 800-53 Rev.5 IR-4, IR-5 · NIST CSF 2.0 DE.AE 3-4.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Incident Management".',
                'policy_code' => 'POL-007',
            ],
            [
                'code' => 'CTRL-IR-002',
                'name' => 'Incident response procedure',
                'description' => 'Incident response procedure. TSH policy/document: PROC-202, PROC-218. Evidence: PROC-202; Playbooks PROC-218. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.26 · NIST SP 800-53 Rev.5 IR-4, IR-8 · NIST CSF 2.0 RS.MA 3-4.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Incident Management".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-IR-003',
                'name' => 'Client notification — 24h SLA',
                'description' => 'Client notification — 24h SLA. TSH policy/document: POL-007, PROC-217. Evidence: PROC-217 notification templates. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.24 · NIST SP 800-53 Rev.5 IR-6, CP-2 · NIST CSF 2.0 RS.CO 3-4.',
                'control_type' => 'Corrective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Incident Management".',
                'policy_code' => 'POL-007',
            ],
            [
                'code' => 'CTRL-IR-004',
                'name' => 'Regulatory notification — GDPR 72h / PDPL 72h',
                'description' => 'Regulatory notification — GDPR 72h / PDPL 72h. TSH policy/document: PROC-205, PROC-217. Evidence: PROC-217 Templates #2/#3. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.24 · NIST SP 800-53 Rev.5 IR-6 · NIST CSF 2.0 RS.CO 3-4 · ISO/IEC 27701:2019 6.4.',
                'control_type' => 'Corrective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Incident Management".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-IR-005',
                'name' => 'Incident register and lessons learned',
                'description' => 'Incident register and lessons learned. TSH policy/document: REG-009, PROC-202. Evidence: REG-009 Incident Register. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.27 · NIST SP 800-53 Rev.5 IR-4, PM-6 · NIST CSF 2.0 RS.AN 3-4.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Incident Management".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-IR-006',
                'name' => 'Security monitoring — 4-platform native (no-SIEM)',
                'description' => 'Security monitoring — 4-platform native (no-SIEM). TSH policy/document: POL-014. Evidence: POL-014 (no-SIEM statement). Framework mapping: ISO/IEC 27001:2022 Annex A A.8.16 · NIST SP 800-53 Rev.5 AU-6, SI-4 · NIST CSF 2.0 DE.CM 3-3.',
                'control_type' => 'Detective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Incident Management".',
                'policy_code' => 'POL-014',
            ],
            [
                'code' => 'CTRL-BCP-001',
                'name' => 'BCP/DR policy — ISO 22301:2019 aligned',
                'description' => 'BCP/DR policy — ISO 22301:2019 aligned. TSH policy/document: POL-008 v2.2. Evidence: Policy Manual (POL-008). Framework mapping: ISO/IEC 27001:2022 Annex A A.5.29 · NIST SP 800-53 Rev.5 CP-2, CP-9 · NIST CSF 2.0 RC.RP 3-5.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Business Continuity".',
                'policy_code' => 'POL-008',
            ],
            [
                'code' => 'CTRL-BCP-002',
                'name' => 'Business Impact Analysis',
                'description' => 'Business Impact Analysis. TSH policy/document: PROC-216. Evidence: PROC-216 BIA document. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.30 · NIST SP 800-53 Rev.5 CP-2, RA-9 · NIST CSF 2.0 ID.BE 3-5.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Business Continuity".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-BCP-003',
                'name' => 'BC/DR incident notification — 2h SLA',
                'description' => 'BC/DR incident notification — 2h SLA. TSH policy/document: POL-008 v2.2. Evidence: POL-008 (Section 2). Framework mapping: ISO/IEC 27001:2022 Annex A A.5.29 · NIST SP 800-53 Rev.5 CP-2, IR-6 · NIST CSF 2.0 RS.CO 3-5.',
                'control_type' => 'Corrective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Business Continuity".',
                'policy_code' => 'POL-008',
            ],
            [
                'code' => 'CTRL-BCP-004',
                'name' => 'Backup & recovery runbook',
                'description' => 'Backup & recovery runbook. TSH policy/document: REF-020. Evidence: REF-020 Recovery Runbook. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.13 · NIST SP 800-53 Rev.5 CP-9, CP-10 · NIST CSF 2.0 RC.RP 3-5.',
                'control_type' => 'Corrective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Business Continuity".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-DATA-001',
                'name' => 'GDPR — as Processor (client projects)',
                'description' => 'GDPR — as Processor (client projects). TSH policy/document: POL-009, CLT-403. Evidence: CLT-403 DPA template. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.34 · NIST SP 800-53 Rev.5 PT-1, AR-1 · NIST CSF 2.0 GV.PO · ISO/IEC 27701:2019 5.3.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Data Protection & Privacy".',
                'policy_code' => 'POL-009',
            ],
            [
                'code' => 'CTRL-DATA-002',
                'name' => 'PDPL (KSA) — alignment as Processor',
                'description' => 'PDPL (KSA) — alignment as Processor. TSH policy/document: POL-009, CLT-403. Evidence: REG-014 K-01/K-02. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.34 · NIST SP 800-53 Rev.5 PT-1 · NIST CSF 2.0 GV.PO · ISO/IEC 27701:2019 6.1.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Data Protection & Privacy".',
                'policy_code' => 'POL-009',
            ],
            [
                'code' => 'CTRL-DATA-003',
                'name' => 'Data classification and handling',
                'description' => 'Data classification and handling. TSH policy/document: POL-002 v2.2. Evidence: POL-002 (Policy Manual). Framework mapping: ISO/IEC 27001:2022 Annex A A.5.12 · NIST SP 800-53 Rev.5 MP-3, MP-4 · NIST CSF 2.0 PR.DS 4-5 · ISO/IEC 27701:2019 5.4.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Data Protection & Privacy".',
                'policy_code' => 'POL-002',
            ],
            [
                'code' => 'CTRL-DATA-004',
                'name' => 'Data deletion — 30 days post-project',
                'description' => 'Data deletion — 30 days post-project. TSH policy/document: PROC-210. Evidence: PROC-210 Offboarding checklist. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.10 · NIST SP 800-53 Rev.5 MP-6, MP-7 · NIST CSF 2.0 PR.DS · ISO/IEC 27701:2019 7.3.5.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Data Protection & Privacy".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-DATA-005',
                'name' => 'ISO 27701 PIMS alignment (privacy management)',
                'description' => 'ISO 27701 PIMS alignment (privacy management). TSH policy/document: POL-009, CLT-403. Evidence: POL-009 + CLT-403. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.34 · NIST SP 800-53 Rev.5 PT-1 to PT-8 · NIST CSF 2.0 GV.PO · ISO/IEC 27701:2019 Multiple.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Data Protection & Privacy".',
                'policy_code' => 'POL-009',
            ],
            [
                'code' => 'CTRL-TPRM-001',
                'name' => 'Third-party risk programme — 4-tier',
                'description' => 'Third-party risk programme — 4-tier. TSH policy/document: POL-006 v2.2. Evidence: REG-010 Third-Party Register. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.19 · NIST SP 800-53 Rev.5 SR-3, SR-5 · NIST CSF 2.0 ID.SC 2-3.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Supply Chain & Third-party".',
                'policy_code' => 'POL-006',
            ],
            [
                'code' => 'CTRL-TPRM-002',
                'name' => 'Sub-contractor equivalent controls requirement',
                'description' => 'Sub-contractor equivalent controls requirement. TSH policy/document: POL-006 v2.2, REF-019. Evidence: POL-006 (Policy Manual). Framework mapping: ISO/IEC 27001:2022 Annex A A.5.20 · NIST SP 800-53 Rev.5 SR-3, PS-7 · NIST CSF 2.0 ID.SC 2-3.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Supply Chain & Third-party".',
                'policy_code' => 'POL-006',
            ],
            [
                'code' => 'CTRL-TPRM-003',
                'name' => 'DPA with all vendors processing personal data',
                'description' => 'DPA with all vendors processing personal data. TSH policy/document: CLT-403, REG-010. Evidence: REG-010 DPA status column. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.19 · NIST SP 800-53 Rev.5 SA-4, SR-3 · NIST CSF 2.0 ID.SC · ISO/IEC 27701:2019 6.6.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Supply Chain & Third-party".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-TPRM-004',
                'name' => 'DORA Art. 28 provisions for financial clients',
                'description' => 'DORA Art. 28 provisions for financial clients. TSH policy/document: CLT-404, CLT-408. Evidence: CLT-408 Exit Plan; CLT-409 Data Location. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.19 · NIST SP 800-53 Rev.5 SR-3 · NIST CSF 2.0 ID.SC.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Supply Chain & Third-party".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-PPL-001',
                'name' => 'Pre-employment screening',
                'description' => 'Pre-employment screening. TSH policy/document: REF-021. Evidence: REF-021 Vetting Template. Framework mapping: ISO/IEC 27001:2022 Annex A A.6.1 · NIST SP 800-53 Rev.5 PS-3, PS-4 · NIST CSF 2.0 GV.RR 5-2.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "People & Awareness".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-PPL-002',
                'name' => 'Anti-bribery & anti-corruption policy',
                'description' => 'Anti-bribery & anti-corruption policy. TSH policy/document: POL-018. Evidence: POL-018 ABAC Policy. Framework mapping: ISO/IEC 27001:2022 Annex A A.6.2 · NIST SP 800-53 Rev.5 PM-1 · NIST CSF 2.0 GV.PO 1-2.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "People & Awareness".',
                'policy_code' => 'POL-018',
            ],
            [
                'code' => 'CTRL-PPL-003',
                'name' => 'Security awareness training — all staff',
                'description' => 'Security awareness training — all staff. TSH policy/document: PROC-207, TRN-001. Evidence: REG-017 Training Master Plan. Framework mapping: ISO/IEC 27001:2022 Annex A A.6.3 · NIST SP 800-53 Rev.5 AT-2, PL-4 · NIST CSF 2.0 GV.AT 5-1.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "People & Awareness".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-PPL-004',
                'name' => 'Role-specific security training',
                'description' => 'Role-specific security training. TSH policy/document: TRN-002–007. Evidence: 7 department syllabuses. Framework mapping: ISO/IEC 27001:2022 Annex A A.6.3 · NIST SP 800-53 Rev.5 AT-3 · NIST CSF 2.0 GV.AT 5-1.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "People & Awareness".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-PPL-005',
                'name' => 'NDA and confidentiality agreements',
                'description' => 'NDA and confidentiality agreements. TSH policy/document: POL-006 v2.2, CLT-404. Evidence: Standard NDA + Security Requirements. Framework mapping: ISO/IEC 27001:2022 Annex A A.6.6 · NIST SP 800-53 Rev.5 PS-6, SA-4 · NIST CSF 2.0 GV.PO.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Client audit right: Yes (under NDA). Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "People & Awareness".',
                'policy_code' => 'POL-006',
            ],
            [
                'code' => 'CTRL-PHYS-001',
                'name' => 'Remote work physical security requirements',
                'description' => 'Remote work physical security requirements. TSH policy/document: POL-011. Evidence: POL-011 Physical Security. Framework mapping: ISO/IEC 27001:2022 Annex A A.7.1 · NIST SP 800-53 Rev.5 PE-17, MP-4 · NIST CSF 2.0 PR.PS.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => '[v3.1] Not represented in the current Control Mapping Matrix (v3.1, 2026-07-14) — the "Physical Security" domain was dropped from the matrix. The governing policy (POL-011) remains active and unchanged; this control record is preserved for continuity (linked Findings/Evidence/Tests) but is flagged not applicable pending CSO clarification on whether it should be retired or re-added to a future matrix revision. Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Physical Security".',
                'policy_code' => 'POL-011',
                'is_applicable' => false,
            ],
            [
                'code' => 'CTRL-PHYS-002',
                'name' => 'Screen lock and clear desk',
                'description' => 'Screen lock and clear desk. TSH policy/document: POL-012. Evidence: POL-012 Clear Desk & Screen. Framework mapping: ISO/IEC 27001:2022 Annex A A.7.7 · NIST SP 800-53 Rev.5 PE-5 · NIST CSF 2.0 PR.PS.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => '[v3.1] Not represented in the current Control Mapping Matrix (v3.1, 2026-07-14) — the "Physical Security" domain was dropped from the matrix. The governing policy (POL-012) remains active and unchanged; this control record is preserved for continuity (linked Findings/Evidence/Tests) but is flagged not applicable pending CSO clarification on whether it should be retired or re-added to a future matrix revision. Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Physical Security".',
                'policy_code' => 'POL-012',
                'is_applicable' => false,
            ],
            [
                'code' => 'CTRL-PHYS-003',
                'name' => 'Device loss/theft response — IRU remote wipe',
                'description' => 'Device loss/theft response — IRU remote wipe. TSH policy/document: POL-011, PROC-202. Evidence: IRU/Intune wipe procedures. Framework mapping: ISO/IEC 27001:2022 Annex A A.7.9 · NIST SP 800-53 Rev.5 MP-5, IR-4 · NIST CSF 2.0 RS.MA 4-3.',
                'control_type' => 'Corrective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => '[v3.1] Not represented in the current Control Mapping Matrix (v3.1, 2026-07-14) — the "Physical Security" domain was dropped from the matrix. The governing policy (POL-011) remains active and unchanged; this control record is preserved for continuity (linked Findings/Evidence/Tests) but is flagged not applicable pending CSO clarification on whether it should be retired or re-added to a future matrix revision. Source: TSH-SEC-REF-MAPPING v3.0 (Control Mapping Matrix), domain "Physical Security".',
                'policy_code' => 'POL-011',
                'is_applicable' => false,
            ],

            // --- New in TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14) ---
            [
                'code' => 'CTRL-GOV-010',
                'name' => 'Segregation of duties — CSO/IT/Tech Lead independence',
                'description' => 'Segregation of duties — CSO/IT/Tech Lead independence. TSH policy/document: POL-001 v2.4. Evidence: Org chart, access reviews. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.3 · NIST SP 800-53 Rev.5 AC-5 · NIST CSF 2.0 GV.RR.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Governance & Policy".',
                'policy_code' => 'POL-001',
            ],
            [
                'code' => 'CTRL-NET-005',
                'name' => 'Cloud security — hyperscaler-only, NCA CCC-1:2020 alignment for KSA hosting',
                'description' => 'Cloud security — hyperscaler-only (GCP/Azure/AWS), client-managed or shared responsibility; NCA CCC-1:2020 alignment for KSA-hosted projects. TSH policy/document: POL-009 v2.1, CFG-301, CLT-409. Evidence: Cloud architecture docs under NDA; CLT-409 Data Location Statement. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.23 · NIST SP 800-53 Rev.5 SC-7, SA-9 · NIST CSF 2.0 PR.IR/GV.PO. KSA-specific: NCA CCC-1:2020.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Network & Cloud Security".',
                'policy_code' => 'POL-009',
            ],
            [
                'code' => 'CTRL-NET-006',
                'name' => 'DNS-over-HTTPS + Enhanced Safe Browsing',
                'description' => 'DNS-over-HTTPS + Enhanced Safe Browsing (CFG-307). TSH policy/document: CFG-307. Evidence: Chrome Enterprise policy export. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.20 · NIST SP 800-53 Rev.5 SC-7 · NIST CSF 2.0 PR.IR.',
                'control_type' => 'Preventive',
                'automation_level' => 'Automated',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Network & Cloud Security".',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-VULN-001',
                'name' => 'Vulnerability management programme — tiered SLA (Critical 48h, High 7d, Medium 30d, Low 90d)',
                'description' => 'Vulnerability management programme with CVSS-based remediation SLAs across code, infrastructure and endpoints. TSH policy/document: POL-020 v1.0, PROC-203. Evidence: Vulnerability tracker, patch reports. Framework mapping: ISO/IEC 27001:2022 Annex A A.8.8 · NIST SP 800-53 Rev.5 RA-5, SI-2 · NIST CSF 2.0 ID.RA.',
                'control_type' => 'Corrective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Vulnerability Management" (new domain in v3.1).',
                'policy_code' => 'POL-020',
            ],
            [
                'code' => 'CTRL-DATA-006',
                'name' => 'Data subject rights handling — GDPR/PDPL/CCPA',
                'description' => 'Data subject rights handling covering GDPR, PDPL and CCPA/CPRA (access, erasure, correction, portability, opt-out). TSH policy/document: POL-009 v2.1, PROC-218. Evidence: PROC-218 DSR procedure. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.34 · NIST SP 800-53 Rev.5 PT-2, PT-4 · NIST CSF 2.0 GV.PO. KSA-specific: PDPL Implementing Regulations (SDAIA). US-specific: CCPA/CPRA data subject rights.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Privacy & Data Protection" (new domain in v3.1).',
                'policy_code' => 'POL-009',
            ],
            [
                'code' => 'CTRL-DATA-007',
                'name' => 'Privacy by design — DPIA process for high-risk processing',
                'description' => 'Privacy by design with a DPIA process triggered for high-risk processing activities. TSH policy/document: POL-009 v2.1, PROC-218. Evidence: DPIA template. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.34 · NIST SP 800-53 Rev.5 PT-3 · NIST CSF 2.0 GV.PO.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Privacy & Data Protection" (new domain in v3.1).',
                'policy_code' => 'POL-009',
            ],
            [
                'code' => 'CTRL-DATA-008',
                'name' => 'Cross-border data transfers — SCCs / adequacy decisions',
                'description' => 'Cross-border personal data transfers governed by Standard Contractual Clauses or adequacy decisions. TSH policy/document: POL-009 v2.1. Evidence: CLT-403 Transfer Mechanism Annex. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.34 · NIST SP 800-53 Rev.5 PT-7 · NIST CSF 2.0 GV.PO.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Privacy & Data Protection" (new domain in v3.1).',
                'policy_code' => 'POL-009',
            ],
            [
                'code' => 'CTRL-PPL-006',
                'name' => 'Phishing simulation programme — quarterly, ≤5% click-rate target',
                'description' => 'Quarterly phishing simulation across all personnel; results feed the KPI dashboard. Clicking is not punished — it triggers mandatory 5-day microtraining. TSH policy/document: POL-019 v1.0, PROC-206. Evidence: Phishing platform reports, KPI (REG-013). Framework mapping: ISO/IEC 27001:2022 Annex A A.6.3 · NIST SP 800-53 Rev.5 AT-2(2) · NIST CSF 2.0 PR.AT.',
                'control_type' => 'Detective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'quarterly',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "People & Awareness".',
                'policy_code' => 'POL-019',
            ],
            [
                'code' => 'CTRL-PPL-007',
                'name' => 'Security Champions programme — embedded in dev teams',
                'description' => 'Security Champions programme with a designated representative per engineering team, reviewed quarterly. TSH policy/document: POL-019 v1.0, REG-017. Evidence: Security Champions register (REG-017). Framework mapping: ISO/IEC 27001:2022 Annex A A.6.3 · NIST SP 800-53 Rev.5 AT-3 · NIST CSF 2.0 PR.AT.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'quarterly',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "People & Awareness".',
                'policy_code' => 'POL-019',
            ],
            [
                'code' => 'CTRL-INTL-001',
                'name' => 'NCA ECC declaration for KSA engagements',
                'description' => 'NCA ECC-1:2018 declaration covering the full domain set for Saudi engagements. TSH policy/document: CLT-NCA-001. Evidence: CLT-NCA-001 Declaration. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.36 · NIST SP 800-53 Rev.5 CA-1 · NIST CSF 2.0 GV.PO. KSA-specific: NCA ECC-1:2018 (full domain set).',
                'control_type' => 'Directive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Regional & Jurisdictional Compliance (KSA / USA)" (new domain in v3.1).',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-INTL-002',
                'name' => 'State consumer privacy laws (CCPA/CPRA) — data subject rights',
                'description' => 'US state consumer privacy law compliance (California CCPA/CPRA and comparable state laws) for data subject rights. TSH policy/document: POL-009 v2.1, CLT-403. Evidence: POL-009 + CLT-403. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.34 · NIST SP 800-53 Rev.5 PT-1, PT-2 · NIST CSF 2.0 GV.PO. US-specific: CCPA/CPRA (California); comparable state laws (VA, CO, CT, UT, etc.).',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Regional & Jurisdictional Compliance (KSA / USA)" (new domain in v3.1).',
                'policy_code' => 'POL-009',
            ],
            [
                'code' => 'CTRL-INTL-003',
                'name' => 'SOC 2 posture — Trust Services Criteria alignment (not certified)',
                'description' => 'SOC 2 Trust Services Criteria alignment maintained for reference, without formal certification. TSH policy/document: Control Mapping Matrix (this doc). Evidence: Control Mapping Matrix + evidence under NDA. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.1 · NIST SP 800-53 Rev.5 CA-2 · NIST CSF 2.0 GV.OC. US-specific: AICPA SOC 2 Trust Services Criteria — aligned, not certified.',
                'control_type' => 'Directive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Regional & Jurisdictional Compliance (KSA / USA)" (new domain in v3.1).',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-INTL-004',
                'name' => 'GLBA / FFIEC safeguards expectations — financial-sector US clients',
                'description' => 'GLBA Safeguards Rule and FFIEC IT Examination Handbook vendor-management expectations for US financial clients. TSH policy/document: POL-006 v2.2, CLT-404. Evidence: POL-006 + CLT-404. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.19 · NIST SP 800-53 Rev.5 SR-3 · NIST CSF 2.0 ID.SC. US-specific: GLBA Safeguards Rule; FFIEC IT Examination Handbook expectations.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Regional & Jurisdictional Compliance (KSA / USA)" (new domain in v3.1).',
                'policy_code' => 'POL-006',
            ],
            [
                'code' => 'CTRL-INTL-005',
                'name' => 'PCI DSS — cardholder data (not applicable)',
                'description' => 'PCI DSS scope statement: TSH does not store, process, or transmit cardholder data. TSH policy/document: POL-002 v2.2. Evidence: POL-002 — scope statement. US-specific: PCI DSS — out of scope; TSH does not store/process/transmit cardholder data.',
                'control_type' => 'Directive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Not Applicable',
                'applicability_statement' => 'Out of scope — TSH does not process cardholder data. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Regional & Jurisdictional Compliance (KSA / USA)" (new domain in v3.1).',
                'policy_code' => 'POL-002',
                'is_applicable' => false,
            ],
            [
                'code' => 'CTRL-INTL-006',
                'name' => 'State data-breach notification laws — client notification SLA',
                'description' => 'US state data-breach notification statutes; TSH\'s 24h client notification SLA meets or exceeds typical state windows. TSH policy/document: PROC-205, PROC-217. Evidence: PROC-217 Templates + 24h client SLA. Framework mapping: ISO/IEC 27001:2022 Annex A A.5.24 · NIST SP 800-53 Rev.5 IR-6 · NIST CSF 2.0 RS.CO. US-specific: State breach-notification statutes (e.g., CA Civ. Code §1798.82 and equivalents).',
                'control_type' => 'Corrective',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Regional & Jurisdictional Compliance (KSA / USA)" (new domain in v3.1).',
                'policy_code' => null,
            ],
            [
                'code' => 'CTRL-INTL-007',
                'name' => 'Export control screening (EAR/OFAC) — personnel and sub-processors',
                'description' => 'US Export Administration Regulations (EAR) / OFAC sanctions screening applied to personnel and sub-processors. TSH policy/document: POL-006 v2.2, REF-021. Evidence: REF-021 Vetting Template. Framework mapping: ISO/IEC 27001:2022 Annex A A.6.1 · NIST SP 800-53 Rev.5 PS-3 · NIST CSF 2.0 GV.RR. US-specific: US Export Administration Regulations (EAR) / OFAC sanctions screening.',
                'control_type' => 'Preventive',
                'automation_level' => 'Manual',
                'testing_frequency' => 'annual',
                'testing_method' => 'Examination',
                'effectiveness_status' => 'Effective',
                'applicability_statement' => 'Aligned — not certified. Source: TSH-SEC-Control-Mapping-Matrix v3.1 (2026-07-14), domain "Regional & Jurisdictional Compliance (KSA / USA)" (new domain in v3.1).',
                'policy_code' => 'POL-006',
            ],
        ];
    }

    public function run(): void
    {
        $cisoId = User::where('email', 'ciso@grc.local')->value('id');

        DB::transaction(function () use ($cisoId): void {
            foreach ($this->items() as $item) {
                Control::updateOrCreate(
                    ['code' => $item['code']],
                    [
                        'name' => $item['name'],
                        'description' => $item['description'],
                        'control_type' => $item['control_type'],
                        'automation_level' => $item['automation_level'],
                        'owner_id' => $cisoId,
                        'testing_frequency' => $item['testing_frequency'],
                        'testing_method' => $item['testing_method'],
                        'effectiveness_status' => $item['effectiveness_status'],
                        'is_applicable' => $item['is_applicable'] ?? true,
                        'applicability_statement' => $item['applicability_statement'],
                    ]
                );
            }
        });
    }
}
